/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.61"

    // Apply the application plugin to add support for building a CLI application.
    application
}

group = "com.github.bsfowlie.kotlin.tdd.snake"
version = "1.0-SNAPSHOT"

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
//    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation(Deps.kotlin_stdlib_jdk8)

    // Use the AssertJ assertions library
    testImplementation(TestingDeps.assertj)

    // Use the Kotlin test library.
    testImplementation(TestingDeps.junit_jupiter)

    // Use the Kotlin JUnit integration.
    testRuntimeOnly(TestingDeps.junit_jupiter_runtime)
}

application {
    // Define the main class for the application.
    mainClassName = "com.github.bsfowlie.kotlin.tdd.snake.MainKt"
}

tasks.test {
    useJUnitPlatform()
    systemProperties( Pair(
        "junit.jupiter.testinstance.lifecycle.default", "per_class"
    ) )
}
