/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.bsfowlie.kotlin.tdd.snake

import org.assertj.core.api.WithAssertions;
import org.junit.jupiter.api.Test

class MainTest : WithAssertions {
    @Test fun `main has a greeting`() {
        val classUnderTest = Main()
        assertThat(classUnderTest.greeting).describedAs("app should have a greeting").isNotNull()
    }
}
